name: Enforce Branch Naming

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [ main, develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release|docs|chore)\/.+$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch name must start with feature/, bugfix/, hotfix/, release/, docs/, or chore/"
            exit 1
          fi
