name: Enforce Branch Naming

on:
  pull_request:
    branches: [ develop ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/.+$ ]]; then
            echo "❌ Invalid branch name: $BRANCH_NAME"
            echo "Branch name must start with feature/, bugfix/, hotfix/, or release/"
            exit 1
          fi